---
title: "Sea Grant Narrative 2017"
author: "Dan Ovando"
bibliography: Dissertation.bib
output:
  pdf_document: default
  html_document: default
subtitle: 'Period: 08-01-2016 to 04-30-2017'
biblio-style: apalike
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F)
```

# Activity Update

The original proposal for this project centered on utilizing data from marine protected area (MPA) monitoring to provide dynamic estimates of fishery status in data-limited contexts. In the course of developing this project and collaboration with colleagues at the University of Washington, it became clear that this proposed project overlapped strongly with methods already being developed by another student. As a result, following consultation with my dissertation committee and my Sea Grant mentor, Dr. Jason Cope, we elected to pivot my project in a new direction. My new focus is development of methods for integrating economic information into data-limited stock assessment, focusing on data from the Channel Islands region of California as a case study.

# Principal Objectives

Many fisheries around the world require management guidance but lack the robust data streams that underpin state-of-the art fisheries management. To resolve this problem, a large and growing suite of "data-limited stock assessments" (DLAs) have emerged, designed to provide management advice using relatively minimal data (but generous assumptions). Interestingly though, nearly all of the quantitative DLAs established rely exclusively on fish-centric data, for example length frequency distributions [e.g. @Gedamke2006; @Hoenig1983; @Hordyk2016], catch data [e.g. models summarized in @Rosenberg2017; @Carruthers2014]. While these data are clearly critical to proper understanding of a fishery's status, they also ignore the potential light that the economic history of a fishery may shed on its current biological status. This project proposes to address this challenge, by developing a quantitative method for integrating economic information into the stock assessment process, which we can loosely term economic-DLAs (eDLAs).

Length-based DLAs provide a useful entry point for this process. Length-based approaches often rely on equilibrium assumptions in order to "account" for potential recruitment fluctuations. However, this assumption is rarely justified. Attempts to relax this assumption can be hampered by the difficulties in separating changes and trends in recruitment from changes in fishing mortality. I propose to address this challenge by utilizing economic data to set informative priors on the rate of change of fishing mortality, providing a new stream of data for data-limited contexts, and providing a framework for the formal integration of economic data into stock assessment.

Fisheries are inherently economic institutions. @Gordon1954 explained how economic incentives explain the development of a fishing industry. @Hardin1968 extended these principles to make the case that left unregulated these economic incentives would lead to the inevitable over-exploitation of fishery resources. @Ostrom1990 showed that this tragedy could be avoided given an improved set of economic incentives. While fisheries science has generally been focused on measuring the effects of fishing behavior on fish populations [@Smith1994a], it is clear that economic factors substantially drive the fate of fished populations.

It is reasonable to conclude then that the economic history of a fishery can help explain its biological history. How is this of use to us? If we have data on effort and catches, manifestations of economic incentives, over time, why are the incentives that produced those values important to us if we can simply plug these data into our models? While exhaustive time series of catch and CPUE are available in the more valuable and data-rich fisheries of the world, these data are unavailable for the vast majority of fisheries around the world at scales relevant to management (national level catch statistics such as those reported by the FAO are useful but often not applicable to local-scale management decisions). To date, assessments in these data-limited situations have largely restricted themselves to making the most out of whatever individual sources of biological data are available. The premise of this project is that economic data can provide clues as to trends in fishing effort, and by extension potentially mortality and catches, even if total measures of effort, catches, and mortality are themselves unavailable. By integrating economic data, this eDLA process process can help address two critical shortcomings in most currently applied DLAs.

First, the vast majority of DLAs are centered on use of one stream of data. This is both due to practical realities (in many cases only one source of biological data are available), and model simplification. However, basing management solely on one stream of evidence is risky at best. Integrating economic data can provide a second stream of information that can commonly be collected, even if alternative sources of biological data are inaccessible. This proposed eDLA framework provides a method for formally utilizing a perhaps more readily available and informative stream of data that generally goes untouched in data-limited fisheries.

Second, length based methods in particular are among the most prevalent methods of DLA, and to good reason. Robust sampling of length frequencies can provide a quick and cheap estimate of stock status, even with only one year of data [e.g. @Hordyk2016]. However, the performance of these methods is highly dependent on the validity of key assumptions, particularly that the population is at equilibrium, and that recruitment deviates are on average 0 (and are not strongly autocorrelated). Violation of these assumptions can lead to dramatically incorrect estimates of stock status. Ideally then we would like to relax these strict equilibrium assumptions, for example by explicitly estimating recruitment deviates over time from a time series of length data. However, given solely length data, it can be very difficult to separate recruitment pulses from changes in fishing mortality. This proposed framework seeks to resolve this challenge by providing informative priors (or outright estimates) on changes of fishing mortality rate over time, allowing for improved estimates of fishing mortality and recruitment deviates over time from primarily length-based DLAs.

Taken together then, the goal of this project is provide a quantitative framework for integrating often present but rarely used economic data into DLAs. Successfully applied, this approach will help provide an additional stream of information with which to interpret stock status and guide management, as well as improve the ability of length-based DLAs to operate in non-equilibrium conditions.

# Methods

The goal of the proposed model is to fit a model of the general form

$(f_{t},r_{t},d_{t} | l_{t}) \propto (l_{t} | f_{t},r_{t},d_{t},s)(r_{t} | h(d_{t}))(f_{t} | g(p_{t}))$

where *t* is time, *f* is fishing mortality, *r* is recruitment, *d* is relative stock depletion, *l* represents the sampled length distribution, *s* are data on selectivities, $h(d_{t})$ reflects a stock recruitment relationship, and $g(p_{t})$ represents our hypothesized relationship between measures of profits *p* and fishing mortality *f*. The emphasis of this project will be on elaborating the form and structure of the process  $(f_{t} | g(p_{t}))$

Consider for example a case where $f_{t}$ is modeled as a random walk process, where ($f_{t} | [f_{t-1},\sigma_{f}])$. Suppose that we incorporated a standard open-access fleet model into this process. Under this process, we model $f_{t} = f_{t - 1} + \alpha{p_{t - 1}}$ (where p are profits). Given estimates of $p$ and $\alpha$ (and of course assumption that this functional form is correct), we could integrate this process into our random walk model, such that $f_{t}$ is modeled using a form $f_{t} | f_{t - 1}, p_{t-1}, \alpha$, with appropriate priors as can be parameterized.

The first phase of this project will entail empirical examination of the relationships between economic indicators (such as prices and costs) and fishing mortality rates. The key assumption behind this project is that fishing effort, and by extension mortality, is guided to at least some significant degree by economic incentives. Given this assumption then, data such as prices and costs, which affect fishing profits and therefore economic incentives, should be predictive of observed changes in fishing effort. While there has been substantial growth in studies of the behaviors of fishing fleets [e.g. @Branch2006; @vanPutten2012; @Quaas2015], these studies have focused on understanding and simulating the drivers of fishing behavior, and the ways that effective management plans can be designed around these behaviors. There is surprisingly little empirical evidence directly examining the ability of economic drivers to predict historic fishery metrics such as fishing mortality [see @Marchal2013 for an example of estimating catches based on economic drivers].

My personal theory for this lack of information is that much of the work in this field has developed in data-rich fisheries that have access to historic time series of catch and effort, removing the explicit need of modeling why these catches and effort arose and how those incentives map onto fishery metrics. However, our goal is to ask, if you know something about economic incentives, can you predict metrics such as fishing mortality, without the intermediate raw data of catches or total effort? To that end, this project will select a set of appropriate case study fisheries with sufficient time series of data on economic indicators (e.g. prices, costs), fishing effort, and fishing mortality, and build off of economic production models to estimate and evaluate alternative empirical relationships between these metrics. The goal of this phase will be to examine the ability of economic models to estimate relative changes in fishing mortality, and in doing so parameterize functional forms for the incorporation of economic data into DLAs.

The second phase of this project will be to simulation test the performance of our proposed eDLA under an exhaustive range of plausible fishery scenarios. This will evaluate the ability of this proposed assessment methodology to improve estimates of fishing mortality and population status, compared to traditional DLA methods. A key facet of this phase will be identifying under what economic "states of the world" this proposed method functions (e.g., classic open access dynamics, long-term profit maximization, risk minimization, catch smoothing), as each of these states would produce different expected relationships between economic indicators and fishing mortality.

The third phase of this project, conditional on promising results from phase one and two will be application of the eDLA to appropriate species in California. Extensive time series of length frequency data are available for many commercially exploited finfish along the California coast (e.g. visual survey monitoring by [PISCO](http://www.piscoweb.org/publications/outreach-materials/ChannelIslands10years), or experimental fishing by the  Sea Grant supported [California Collaborative Fisheries Research Program](https://seagrant.mlml.calstate.edu/research/ccfrp/)). In, theory these data could be used to fit length-based DLAs such as Length-Based Spawning Potential Ratio [LBSPR; @Hordyk2016]. However, cursory exploration of the data reveals clear trends and changes in landings and length structures of these populations over time, indicating likely violation of the equilibrium assumptions required for LBSPR. I intend to overcome this assessment challenge by integrating these length data with historic economic data from the region (for example those available from the [OceanSpaces](http://oceanspaces.org/data) project) through this proposed eDLA, providing improved estimates of stock status for important California fisheries. In addition, successful application of this method will help demonstrate the value of fishery independent monitoring programs such as CCFRP for localized stock assessment.

# Results/Outcomes

As a result of the pivot to this project, I am still in the development phase of this eDLA concept. I traveled to Seattle in February to meet with Jason Cope and scientists at the Northwest Fisheries Science Center to launch this pivot. Through this trip, we had several constructive meetings on the merits of thsi idea, and established some potential fisheries to target for the empirical phase of this project, including pacific pollock and fixed-gear sablefish. I have also been developing the operating model that will be used to simulation test this eDLA approach.
8# Future Work

This current proposal is focused on empirical testing of relationships between fishing mortality and economic parameters, and the ability of these relationships to augment length-based DLAs. However, it is conceivable that economic data could also be informative to other types of DLAs. Catch-based DLAs are extremely prevalent, accounting for ~50% of stocks in the United States [@Berkson2015], and several global-scale assessments of stock status [@Costello2012; @Costello2016; @Rosenberg2017]. However, these catch based methods can be severely compromised when changes in catch are not reflective of underlying changes in abundance [@Branch2011], leading to a call for collection of new data, rather than relying on continued attempts to squeeze more information from the same catch histories. This proposed eDLA framework could provide a method for augmenting catch-only DLAs with economic data, for example helping explain dramatic decreases in catch due to changes in market demand or fuel prices, rather than declining stocks.

Future work may also include development of a formal methodology for collecting and integrating economic data for use in eDLAs. This proposed methodology will develop a set of economic metrics that are potentially useful tools for stock assessment, with a goal of improvising DLAs. However, given a data-limited context, it is unlikely that well curated time-series of these data will be available (though when they are this proposed method will allow for the integration of these often overlooked data). In order for this approach to be broadly applicable, we will need to develop a set of guidelines for the types of economic data required, and best practices for collecting these data (through for example community surveys), and translating these data into the parameters of the model.

Lastly, if through the course of this work, it becomes clear that economic indicators are poor predictors of fishery status, that in and of itself gives us an interesting angle. State of the art management strategy evaluation is often based on bioeconomic modeling, in which key assumptions about how fishing fleets react to economic drivers are required. If we can identify little empirical evidence for these often utilized relationships, this suggests that we need to revisit the ways that we think about modeling fleet behaviors. 

# Works Cited
